sizes <- scan("sizes.txt", what = integer(), sep = " ")
simple_totals1 <- scan("simple_totals1.txt", what = integer(), sep = " ")
sieve_totals1 <- scan("sieve_totals1.txt", what = integer(), sep = " ")
simple_totals2 <- scan("simple_totals2.txt", what = integer(), sep = " ")
sieve_totals2 <- scan("sieve_totals2.txt", what = integer(), sep = " ")
simple_totals3 <- scan("simple_totals3.txt", what = integer(), sep = " ")
sieve_totals3 <- scan("sieve_totals3.txt", what = integer(), sep = " ")
simple_totals4 <- scan("simple_totals4.txt", what = integer(), sep = " ")
sieve_totals4 <- scan("sieve_totals4.txt", what = integer(), sep = " ")
name <- "SOLID: SIMPLE (DIVISORS METHOD), DASHED: SIEVE OF ERATOSTHENES\nPURPLE: UPPER_BOUND1 (1e3) BLUE: UPPER_BOUND2 (1e4) GREEN: UPPER_BOUND3 (1e5) RED: UPPER_BOUND4 (1e6)"
options(scipen=5)
x.min.value <- min(sizes)
x.max.value <- max(sizes)
y.min.value <- min(c(simple_totals1, simple_totals2, simple_totals3, simple_totals4, sieve_totals1, sieve_totals2, sieve_totals3, sieve_totals4))
y.max.value <- max(c(simple_totals1, simple_totals2, simple_totals3, simple_totals4, sieve_totals1, sieve_totals2, sieve_totals3, sieve_totals4))
plot(sizes, simple_totals1, type = "l", col = "purple", main = name, xlab = "Array size", ylab = "Time", ylim = c(y.min.value, y.max.value), xlim = c(x.min.value, x.max.value))
lines(sizes, sieve_totals1, type = "l", col = "purple", lty = 5)
lines(sizes, simple_totals2, type = "l", col = "blue")
lines(sizes, sieve_totals2, type = "l", col = "blue", lty = 5)
lines(sizes, simple_totals3, type = "l", col = "green")
lines(sizes, sieve_totals3, type = "l", col = "green", lty = 5)
lines(sizes, simple_totals4, type = "l", col = "red")
lines(sizes, sieve_totals4, type = "l", col = "red", lty = 5)